package variantregistry

import (
	"fmt"
	"sort"
	"strings"
	"testing"

	"github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"

	v1 "github.com/openshift/sippy/pkg/apis/config/v1"
	"github.com/openshift/sippy/pkg/flags/configflags"
)

func TestVariantSyncer(t *testing.T) {
	variantSyncer := OCPVariantLoader{config: &v1.SippyConfig{}}
	tests := []struct {
		job          string
		variantsFile map[string]string
		expected     map[string]string
	}{
		{
			job:          "periodic-ci-redhat-chaos-prow-scripts-main-cr-4.19-nightly-krkn-hub-aws",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "chaos",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-osde2e-main-nightly-4.17-conformance-rosa-classic-sts",
			variantsFile: map[string]string{
				"Platform": "aws", // should be ignored
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "rosa",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "service-delivery",
				VariantTopology:         "ha",
				VariantSuite:            "parallel",
				VariantUpgrade:          VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-gcp-ovn-fips",
			variantsFile: map[string]string{
				"Foo":         "bar",          // should be added
				"CloudRegion": "us-central-1", // should be ignored
			},
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "gcp",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantSecurityMode:     "fips",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				"Foo":                   "bar",
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.19-e2e-osd-ccs-gcp",
			variantsFile: map[string]string{
				"Platform": "gcp", // should be ignored
			},
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "osd-gcp",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "service-delivery",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.19-e2e-rosa-sts-ovn",
			variantsFile: map[string]string{
				"Platform": "aws", // should be ignored
			},
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "rosa",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "service-delivery",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn-conformance",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "hypershift", // hypershift uses it's own installer
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "external",
				VariantSuite:            "parallel",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-single-node-serial",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "single",
				VariantSuite:            "serial",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ovn-arbiter-upgrade",
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantFromRelease:      "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha-arbiter",
				VariantSuite:            "unknown",
				VariantUpgrade:          "micro",
				VariantAggregation:      VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-sno-serial",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "single",
				VariantSuite:            "serial",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-upi-serial",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "upi",
				VariantPlatform:         "vsphere",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "serial",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-proxy",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkAccess:    "proxy",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-nat-instance",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkAccess:    "nat-instance",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-aws-ovn-multi-x-ax",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "heterogeneous",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-aws-ovn-multi-a-a",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "arm64",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.17-periodics-e2e-aws-arm",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "arm64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-powervs-capi-multi-p-p",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "ppc64le",
				VariantInstaller:        "ipi",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-remote-libvirt-multi-z-z",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "s390x",
				VariantInstaller:        "ipi",
				VariantPlatform:         "libvirt",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-multiarch-master-nightly-4.16-upgrade-from-nightly-4.15-ocp-e2e-upgrade-gcp-ovn-heterogeneous",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantFromRelease:      "4.15",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "15",
				VariantArch:             "heterogeneous",
				VariantInstaller:        "ipi",
				VariantPlatform:         "gcp",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "minor",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-sdn-bm-upgrade",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantFromRelease:      "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "sdn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "micro",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-assisted",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "assisted",
				VariantPlatform:         "metal",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-no-network-plugin-no-variant-file",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.11-e2e-no-network-plugin-no-variant-file",
			expected: map[string]string{
				VariantRelease:          "4.11",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "11",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantNetwork:          "sdn", // should default to sdn prior to 4.12
				VariantNetworkStack:     "ipv4",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "release-openshift-origin-installer-e2e-aws-upgrade-4.13-to-4.14-to-4.15-to-4.16-ci",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantFromRelease:      "4.13",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "13",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "multi",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-from-stable-4.13-e2e-aws-sdn-upgrade",
			expected: map[string]string{
				VariantRelease:          "4.15",
				VariantFromRelease:      "4.13",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "15",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "13",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "sdn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "multi",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-with-no-release-info",
			expected: map[string]string{
				VariantArch:           "amd64",
				VariantInstaller:      "ipi",
				VariantNetworkStack:   "ipv4",
				VariantOwner:          "eng",
				VariantSuite:          "unknown",
				VariantTopology:       "ha",
				VariantUpgrade:        VariantNoValue,
				VariantAggregation:    VariantNoValue,
				VariantProcedure:      "none",
				VariantJobTier:        "candidate",
				VariantFeatureSet:     VariantDefaultValue,
				VariantNetworkAccess:  VariantDefaultValue,
				VariantScheduler:      VariantDefaultValue,
				VariantSecurityMode:   VariantDefaultValue,
				VariantCGroupMode:     "v2",
				VariantLayeredProduct: VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-dualstack",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "dual",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-metal-ipi-upgrade-ovn-ipv6",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantFromRelease:      "4.15",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "15",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv6",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "minor",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job: "periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn-upgrade-out-of-change",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantFromRelease:      "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "hidden",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "micro-downgrade",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "cnf",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job:          "periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-payload-control-plane-6nodes",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "perfscale",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-crun",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.18",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "18",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-cgroupsv1",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.18",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "18",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v1",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-virt-ovn-techpreview",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.18",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "18",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       "techpreview",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   "virt",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-virt-ovn-runc-techpreview",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.18",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "18",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       "techpreview",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   "virt",
			},
		},
		{
			job:          "periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-sno-tp-arm-f28",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.18",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "18",
				VariantArch:             "arm64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "gcp",
				VariantProcedure:        "none",
				VariantJobTier:          "hidden",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "qe",
				VariantTopology:         "single",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       "techpreview",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   "none",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-cgroupsv1-crun",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v1",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-cgroupsv1",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v1",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job:          "periodic-ci-openshift-openshift-tests-private-release-4.17-automated-release-aws-ipi-f999",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "automated-release",
				VariantJobTier:          "standard",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "qe",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       "default",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-virt-ovn-techpreview",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       "techpreview",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   "virt",
			},
		},
	}
	for _, test := range tests {
		t.Run(test.job, func(t *testing.T) {
			assert.Equal(t, test.expected,
				variantSyncer.CalculateVariantsForJob(
					logrus.WithField("source", "TestVariantSyncer"),
					test.job,
					test.variantsFile))
		})
	}
}

// TestVariantsSnapshot regenerates variants against the OCP config, and then compares against
// a previously taken snapshot. If variants changed, it will fail and report an error. You can
// run `make update-variants` to update and accept the changes. This lets you easily see the impact
// of modifying the OCP variant syncer.
func TestVariantsSnapshot(t *testing.T) {
	cfgFlags := &configflags.ConfigFlags{
		Path: "../../config/openshift.yaml",
	}
	cfg, err := cfgFlags.GetConfig()
	assert.NoError(t, err)

	log := logrus.WithField("test", "TestVariantsSnapshot")

	snapshot := NewVariantSnapshot(cfg, log)
	newVariants := snapshot.Identify()
	oldVariants, err := snapshot.Load("snapshot.yaml")
	assert.NoError(t, err)

	// Map to collect changes
	summary := make(map[string][]string)

	// Iterate only over jobs that exist in both old and new
	anyFail := 0
	for job, newVars := range newVariants {
		oldVars, exists := oldVariants[job]
		if exists {
			t.Run(job, func(t *testing.T) {
				var changes []string

				// Check for added, changed, and removed variants
				for key, newValue := range newVars {
					if oldValue, ok := oldVars[key]; !ok {
						changeMsg := fmt.Sprintf("Added %s:%s", key, newValue)
						changes = append(changes, changeMsg)
						summary[changeMsg] = append(summary[changeMsg], job)
					} else if oldValue != newValue {
						changeMsg := fmt.Sprintf("Changed %s (%s -> %s)", key, oldValue, newValue)
						changes = append(changes, changeMsg)
						summary[changeMsg] = append(summary[changeMsg], job)
					}
				}

				for key := range oldVars {
					if _, ok := newVars[key]; !ok {
						changeMsg := fmt.Sprintf("Removed %s (was %q)", key, oldVars[key])
						changes = append(changes, changeMsg)
						summary[changeMsg] = append(summary[changeMsg], job)
					}
				}

				if len(changes) > 0 {
					t.Logf("%s:\n%s", job, strings.Join(changes, "\n"))
					t.Fail()
					anyFail++
				}
			})
		}
	}

	// Print summary
	if anyFail > 0 {
		t.Logf("\nSummary of changes:")
		for change, jobs := range summary {
			sort.Strings(jobs)
			t.Logf("%s\n   - %s", change, strings.Join(jobs, "\n   - "))
		}
		t.Logf("\n****** Run `make update-variants` to update the snapshot and accept these changes.")
	}
}
