package variantregistry

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	"gopkg.in/yaml.v3"

	"github.com/openshift/sippy/pkg/apis/api"
	"github.com/openshift/sippy/pkg/apis/api/componentreport/crview"
	"github.com/openshift/sippy/pkg/apis/api/componentreport/reqopts"
	v1 "github.com/openshift/sippy/pkg/apis/config/v1"
	"github.com/openshift/sippy/pkg/flags/configflags"
	"github.com/openshift/sippy/pkg/util/sets"
)

func TestVariantSyncer(t *testing.T) {
	variantSyncer := OCPVariantLoader{config: &v1.SippyConfig{}}
	tests := []struct {
		job          string
		variantsFile map[string]string
		osData       clusterDataOS
		expected     map[string]string
	}{
		{
			job: "aggregated-aws-ovn-upgrade-5.1-minor-release-openshift-release-analysis-aggregator",
			expected: map[string]string{
				VariantRelease:          "5.1",
				VariantReleaseMajor:     "5",
				VariantReleaseMinor:     "1",
				VariantFromRelease:      "5.1",
				VariantFromReleaseMajor: "5",
				VariantFromReleaseMinor: "1",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "hidden",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "minor",
				VariantAggregation:      "aggregated",
				VariantFeatureSet:       "default",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "aggregated-aws-ovn-upgrade-5.1-major-release-openshift-release-analysis-aggregator",
			expected: map[string]string{
				VariantRelease:          "5.1",
				VariantReleaseMajor:     "5",
				VariantReleaseMinor:     "1",
				VariantFromRelease:      "5.1",
				VariantFromReleaseMajor: "5",
				VariantFromReleaseMinor: "1",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "hidden",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "major",
				VariantAggregation:      "aggregated",
				VariantFeatureSet:       "default",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-ci-5.0-upgrade-from-stable-4.22-e2e-aws-upgrade",
			expected: map[string]string{
				VariantRelease:          "5.0",
				VariantReleaseMajor:     "5",
				VariantReleaseMinor:     "0",
				VariantFromRelease:      "4.22",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "22",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "major",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       "default",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-ci-5.10-upgrade-from-stable-5.9-e2e-aws-upgrade",
			expected: map[string]string{
				VariantRelease:          "5.10",
				VariantReleaseMajor:     "5",
				VariantReleaseMinor:     "10",
				VariantFromRelease:      "5.9",
				VariantFromReleaseMajor: "5",
				VariantFromReleaseMinor: "9",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "minor",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       "default",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-multi-network-multi-a-a-techpreview",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "arm64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "vsphere",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       "techpreview",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-redhat-chaos-prow-scripts-main-cr-4.19-nightly-krkn-hub-aws",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "chaos",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-osde2e-main-nightly-4.17-conformance-rosa-classic-sts",
			variantsFile: map[string]string{
				"Platform": "aws", // should be ignored
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "rosa",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "service-delivery",
				VariantTopology:         "ha",
				VariantSuite:            "parallel",
				VariantUpgrade:          VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "excluded",
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-gcp-ovn-fips",
			variantsFile: map[string]string{
				"Foo":         "bar",          // should be added
				"CloudRegion": "us-central-1", // should be ignored
			},
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "gcp",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantSecurityMode:     "fips",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				"Foo":                   "bar",
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.19-e2e-osd-ccs-gcp",
			variantsFile: map[string]string{
				"Platform": "gcp", // should be ignored
			},
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "osd-gcp",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "service-delivery",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.19-e2e-rosa-sts-ovn",
			variantsFile: map[string]string{
				"Platform": "aws", // should be ignored
			},
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "rosa",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "service-delivery",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn-conformance",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "hypershift", // hypershift uses it's own installer
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "standard",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "external",
				VariantSuite:            "parallel",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-hypershift-release-4.20-periodics-e2e-aws-multi",
			expected: map[string]string{
				VariantRelease:          "4.20",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "20",
				VariantArch:             "multi",
				VariantInstaller:        "hypershift", // hypershift uses it's own installer
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "external",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-single-node-serial",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "single",
				VariantSuite:            "serial",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantProcedure:        "serial",
				VariantJobTier:          "candidate",
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ovn-two-node-arbiter-upgrade",
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantFromRelease:      "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "two-node-arbiter",
				VariantSuite:            "unknown",
				VariantUpgrade:          "micro",
				VariantAggregation:      VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ovn-two-node-fencing-upgrade",
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantFromRelease:      "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "two-node-fencing",
				VariantSuite:            "unknown",
				VariantUpgrade:          "micro",
				VariantAggregation:      VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ovn-tna-upgrade",
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantFromRelease:      "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "two-node-arbiter",
				VariantSuite:            "unknown",
				VariantUpgrade:          "micro",
				VariantAggregation:      VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ovn-tnf-upgrade",
			expected: map[string]string{
				VariantRelease:          "4.19",
				VariantFromRelease:      "4.19",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "19",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "19",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "two-node-fencing",
				VariantSuite:            "unknown",
				VariantUpgrade:          "micro",
				VariantAggregation:      VariantNoValue,
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-sno-serial",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "single",
				VariantSuite:            "serial",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantProcedure:        "serial",
				VariantJobTier:          "candidate",
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-upi-serial",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantProcedure:        "serial",
				VariantJobTier:          "candidate",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "upi",
				VariantPlatform:         "vsphere",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "serial",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-proxy",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkAccess:    "proxy",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-ovn-nat-instance",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkAccess:    "nat-instance",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-aws-ovn-multi-x-ax",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "multi",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-multi-vcenter-csi",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "vsphere",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-multi-network-techpreview",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "vsphere",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       "techpreview",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-aws-ovn-multi-a-a",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "arm64",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.17-periodics-e2e-aws-arm",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "arm64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-powervs-capi-multi-p-p",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "ppc64le",
				VariantInstaller:        "ipi",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-remote-libvirt-multi-z-z",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "s390x",
				VariantInstaller:        "ipi",
				VariantPlatform:         "libvirt",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-multiarch-master-nightly-4.16-upgrade-from-nightly-4.15-ocp-e2e-upgrade-gcp-ovn-heterogeneous",
			variantsFile: map[string]string{
				"Architecture": "amd64", // should be overruled by the job parsing.
			},
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantFromRelease:      "4.15",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "15",
				VariantArch:             "multi",
				VariantInstaller:        "ipi",
				VariantPlatform:         "gcp",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "minor",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-sdn-bm-upgrade",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantFromRelease:      "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "sdn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "micro",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-assisted",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "assisted",
				VariantPlatform:         "metal",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-no-network-plugin-no-variant-file",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.11-e2e-no-network-plugin-no-variant-file",
			expected: map[string]string{
				VariantRelease:          "4.11",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "11",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantNetwork:          "sdn", // should default to sdn prior to 4.12
				VariantNetworkStack:     "ipv4",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "release-openshift-origin-installer-e2e-aws-upgrade-4.13-to-4.14-to-4.15-to-4.16-ci",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantFromRelease:      "4.13",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "13",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "multi",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "release-openshift-origin-installer-e2e-aws-upgrade-4.21-to-4.22-to-5.0-ci",
			expected: map[string]string{
				VariantRelease:          "5.0",
				VariantFromRelease:      "4.21",
				VariantReleaseMajor:     "5",
				VariantReleaseMinor:     "0",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "21",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "multi",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-from-stable-4.13-e2e-aws-sdn-upgrade",
			expected: map[string]string{
				VariantRelease:          "4.15",
				VariantFromRelease:      "4.13",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "15",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "13",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "sdn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "multi",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-with-no-release-info",
			expected: map[string]string{
				VariantArch:           "amd64",
				VariantInstaller:      "ipi",
				VariantNetworkStack:   "ipv4",
				VariantOwner:          "eng",
				VariantSuite:          "unknown",
				VariantTopology:       "ha",
				VariantUpgrade:        VariantNoValue,
				VariantAggregation:    VariantNoValue,
				VariantProcedure:      "none",
				VariantJobTier:        "candidate",
				VariantFeatureSet:     VariantDefaultValue,
				VariantNetworkAccess:  VariantDefaultValue,
				VariantScheduler:      VariantDefaultValue,
				VariantSecurityMode:   VariantDefaultValue,
				VariantCGroupMode:     "v2",
				VariantLayeredProduct: VariantNoValue,
				VariantOS:             "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-dualstack",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "dual",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-metal-ipi-upgrade-ovn-ipv6",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantFromRelease:      "4.15",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "15",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "metal",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv6",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "minor",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job: "periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn-upgrade-out-of-change",
			expected: map[string]string{
				VariantRelease:          "4.16",
				VariantFromRelease:      "4.16",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "16",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "16",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "hidden",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "micro-downgrade",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.17-e2e-telco5g",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "cnf",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-nightly-x86-payload-control-plane-6nodes",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "perfscale",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-crun",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.18",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "18",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-cgroupsv1",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.18",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "18",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v1",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-virt-ovn-techpreview",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.18",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "18",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       "techpreview",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   "virt",
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-virt-ovn-runc-techpreview",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.18",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "18",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       "techpreview",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   "virt",
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-sno-tp-arm-f28",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.18",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "18",
				VariantArch:             "arm64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "gcp",
				VariantProcedure:        "none",
				VariantJobTier:          "hidden",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "qe",
				VariantTopology:         "single",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       "techpreview",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   "none",
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-cgroupsv1-crun",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v1",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-cgroupsv1",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v1",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-openshift-tests-private-release-4.17-automated-release-aws-ipi-f999",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "automated-release",
				VariantJobTier:          "standard",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "qe",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       "default",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-virt-ovn-techpreview",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.17",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "17",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "unknown",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       "techpreview",
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "runc",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   "virt",
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.20-e2e-external-aws",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.20",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "20",
				VariantArch:             "amd64",
				VariantInstaller:        "upi",
				VariantPlatform:         "external-aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "parallel",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.20-e2e-external-vsphere-ccm",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.20",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "20",
				VariantArch:             "amd64",
				VariantInstaller:        "upi",
				VariantPlatform:         "external-vsphere",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantTopology:         "ha",
				VariantSuite:            "parallel",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-operator-framework-operator-controller-release-4.20-periodics-default-catalog-consistency",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.20",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "20",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.20-e2e-aws-ovn-serial-ipsec",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.20",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "20",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "serial-ipsec",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "serial",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-RedHatQE-interop-testing-master-cnv-odf-ocp4.20-lp-interop-cnv-component-readiness-aws-ipi-ocp420",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.20",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "20",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "mpiit",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   "virt",
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-hypershift-release-4.20-periodics-e2e-aks",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "4.20",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "20",
				VariantArch:             "amd64",
				VariantInstaller:        "hypershift",
				VariantPlatform:         "azure",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "external",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.20-e2e-aws-rhcos9-10-ovn",
			variantsFile: map[string]string{},
			osData: clusterDataOS{
				ControlPlane: "rhel-9",
				Workers:      "rhel-10",
			},
			expected: map[string]string{
				VariantRelease:          "4.20",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "20",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9-10",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-4.20-e2e-aws-rhcos10-ovn",
			variantsFile: map[string]string{},
			osData: clusterDataOS{
				ControlPlane: "rhcos10",
				Workers:      "rhcos10",
			},
			expected: map[string]string{
				VariantRelease:          "4.20",
				VariantReleaseMajor:     "4",
				VariantReleaseMinor:     "20",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "aws",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          VariantNoValue,
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos10",
			},
		},
		{
			job:          "periodic-ci-openshift-release-master-nightly-5.0-upgrade-from-nightly-4.22-major-e2e-azure",
			variantsFile: map[string]string{},
			expected: map[string]string{
				VariantRelease:          "5.0",
				VariantReleaseMajor:     "5",
				VariantReleaseMinor:     "0",
				VariantFromRelease:      "4.22",
				VariantFromReleaseMajor: "4",
				VariantFromReleaseMinor: "22",
				VariantArch:             "amd64",
				VariantInstaller:        "ipi",
				VariantPlatform:         "azure",
				VariantProcedure:        "none",
				VariantJobTier:          "candidate",
				VariantNetwork:          "ovn",
				VariantNetworkStack:     "ipv4",
				VariantOwner:            "eng",
				VariantSuite:            "unknown",
				VariantTopology:         "ha",
				VariantUpgrade:          "major",
				VariantAggregation:      VariantNoValue,
				VariantFeatureSet:       VariantDefaultValue,
				VariantNetworkAccess:    VariantDefaultValue,
				VariantScheduler:        VariantDefaultValue,
				VariantSecurityMode:     VariantDefaultValue,
				VariantContainerRuntime: "crun",
				VariantCGroupMode:       "v2",
				VariantLayeredProduct:   VariantNoValue,
				VariantOS:               "rhcos9",
			},
		},
	}
	for _, test := range tests {
		t.Run(test.job, func(t *testing.T) {
			assert.Equal(t, test.expected,
				variantSyncer.calculateVariantsForJob(
					logrus.WithField("source", "TestVariantSyncer"),
					test.job,
					test.variantsFile,
					test.osData))
		})
	}
}

// TestVariantsSnapshot regenerates variants against the OCP config, and then compares against
// a previously taken snapshot. If variants changed, it will fail and report an error. You can
// run `make update-variants` to update and accept the changes. This lets you easily see the impact
// of modifying the OCP variant syncer.
func TestVariantsSnapshot(t *testing.T) {
	cfgFlags := &configflags.ConfigFlags{
		Path: "../../config/openshift.yaml",
	}
	cfg, err := cfgFlags.GetConfig()
	assert.NoError(t, err)

	viewsData, err := os.ReadFile("../../config/views.yaml")
	assert.NoError(t, err)
	var views api.SippyViews
	err = yaml.Unmarshal(viewsData, &views)
	assert.NoError(t, err)

	log := logrus.WithField("test", "TestVariantsSnapshot")

	snapshot := NewVariantSnapshot(cfg, views.ComponentReadiness, log)

	newVariants := snapshot.Identify()
	oldVariants, err := snapshot.Load("snapshot.yaml")
	assert.NoError(t, err)

	// Map to collect changes
	summary := make(map[string][]string)

	// Iterate only over jobs that exist in both old and new
	anyFail := 0
	for job, newVars := range newVariants {
		oldVars, exists := oldVariants[job]
		if exists {
			t.Run(job, func(t *testing.T) {
				var changes []string

				// Check for added, changed, and removed variants
				for key, newValue := range newVars {
					if oldValue, ok := oldVars[key]; !ok {
						changeMsg := fmt.Sprintf("Added %s:%s", key, newValue)
						changes = append(changes, changeMsg)
						summary[changeMsg] = append(summary[changeMsg], job)
					} else if oldValue != newValue {
						changeMsg := fmt.Sprintf("Changed %s (%s -> %s)", key, oldValue, newValue)
						changes = append(changes, changeMsg)
						summary[changeMsg] = append(summary[changeMsg], job)
					}
				}

				for key := range oldVars {
					if _, ok := newVars[key]; !ok {
						changeMsg := fmt.Sprintf("Removed %s (was %q)", key, oldVars[key])
						changes = append(changes, changeMsg)
						summary[changeMsg] = append(summary[changeMsg], job)
					}
				}

				if len(changes) > 0 {
					t.Logf("%s:\n%s", job, strings.Join(changes, "\n"))
					t.Fail()
					anyFail++
				}
			})
		}
	}

	// Print summary
	if anyFail > 0 {
		t.Logf("\nSummary of changes:")
		for change, jobs := range summary {
			sort.Strings(jobs)
			t.Logf("%s\n   - %s", change, strings.Join(jobs, "\n   - "))
		}
		t.Logf("\n****** Run `make update-variants` to update the snapshot and accept these changes.")
	}
}

func testView(name string, includeVariants map[string][]string) crview.View {
	return crview.View{
		Name: name,
		VariantOptions: reqopts.Variants{
			ColumnGroupBy:   sets.String{},
			DBGroupBy:       sets.String{},
			IncludeVariants: includeVariants,
		},
	}
}

func TestSetOS(t *testing.T) {
	tests := []struct {
		name          string
		releaseMajor  string
		clusterDataOS clusterDataOS
		expectedOS    string
	}{
		{
			name:         "no cluster data with release major 4 defaults to rhcos9",
			releaseMajor: "4",
			expectedOS:   "rhcos9",
		},
		{
			name:         "no cluster data with release major 5 defaults to rhcos9",
			releaseMajor: "5",
			expectedOS:   "rhcos9",
		},
		{
			name: "mix of rhcos9 and rhcos10 in cp and workers produces rhcos9-10",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhel-9",
				Workers:      "rhel-10",
			},
			expectedOS: "rhcos9-10",
		},
		{
			name: "cluster data with matching control plane and workers",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhcos10",
				Workers:      "rhcos10",
			},
			expectedOS: "rhcos10",
		},
		{
			name: "cluster data with additional matching control plane and workers",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhcos9",
				Workers:      "rhcos9",
				Additional:   []string{"rhcos9"},
			},
			expectedOS: "rhcos9",
		},
		{
			name: "cluster data with rhcos10 additional and rhcos9 pools is rhcos9-10",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhcos9",
				Workers:      "rhcos9",
				Additional:   []string{"rhcos10"},
			},
			expectedOS: "rhcos9-10",
		},
		{
			name: "cluster data with rhcos9 cp and rhcos10 workers is rhcos9-10",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhcos9",
				Workers:      "rhcos10",
			},
			expectedOS: "rhcos9-10",
		},
		{
			name: "cluster data with three different OS values is mixed",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhcos9",
				Workers:      "rhcos10",
				Additional:   []string{"fcos"},
			},
			expectedOS: "mixed",
		},
		{
			name: "default backfills both empty cp and workers",
			clusterDataOS: clusterDataOS{
				Default: "rhcos10",
			},
			expectedOS: "rhcos10",
		},
		{
			name: "default backfills both empty cp and workers but additional is rhcos9-10 mix",
			clusterDataOS: clusterDataOS{
				Default:    "rhcos10",
				Additional: []string{"rhcos9"},
			},
			expectedOS: "rhcos9-10",
		},
		{
			name: "default backfills empty cp to match workers",
			clusterDataOS: clusterDataOS{
				Default: "rhcos9",
				Workers: "rhcos9",
			},
			expectedOS: "rhcos9",
		},
		{
			name: "default backfills empty cp producing rhcos9-10 mix with workers",
			clusterDataOS: clusterDataOS{
				Default: "rhcos9",
				Workers: "rhcos10",
			},
			expectedOS: "rhcos9-10",
		},
		{
			name: "default backfills empty workers to match cp",
			clusterDataOS: clusterDataOS{
				Default:      "rhcos10",
				ControlPlane: "rhcos10",
			},
			expectedOS: "rhcos10",
		},
		{
			name: "default backfills empty workers producing rhcos9-10 mix with cp",
			clusterDataOS: clusterDataOS{
				Default:      "rhcos9",
				ControlPlane: "rhcos10",
			},
			expectedOS: "rhcos9-10",
		},
		{
			name:         "release major 4 backfills default which backfills empty cp and workers",
			releaseMajor: "4",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhcos9",
			},
			expectedOS: "rhcos9",
		},
		{
			name:         "release major backfilled default does not override explicit default",
			releaseMajor: "4",
			clusterDataOS: clusterDataOS{
				Default: "rhcos10",
			},
			expectedOS: "rhcos10",
		},
		{
			name:         "release major backfilled default produces rhcos9-10 mix with cp",
			releaseMajor: "4",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhcos10",
			},
			expectedOS: "rhcos9-10",
		},
		{
			name: "empty string in additional is backfilled from default",
			clusterDataOS: clusterDataOS{
				Default:      "rhcos9",
				ControlPlane: "rhcos9",
				Workers:      "rhcos9",
				Additional:   []string{""},
			},
			expectedOS: "rhcos9",
		},
		{
			name: "empty string in additional backfilled from default produces rhcos9-10 mix",
			clusterDataOS: clusterDataOS{
				Default:      "rhcos10",
				ControlPlane: "rhcos9",
				Workers:      "rhcos9",
				Additional:   []string{""},
			},
			expectedOS: "rhcos9-10",
		},
		{
			name: "rhel-9 stream maps to rhcos9",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhel-9",
				Workers:      "rhel-9",
			},
			expectedOS: "rhcos9",
		},
		{
			name: "rhel-9.6 stream maps to rhcos9",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhel-9.6",
				Workers:      "rhel-9.6",
			},
			expectedOS: "rhcos9",
		},
		{
			name: "rhel-9.6.1 stream maps to rhcos9",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhel-9.6.1",
				Workers:      "rhel-9.6.1",
			},
			expectedOS: "rhcos9",
		},
		{
			name: "rhel-9-nvidia stream maps to rhcos9",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhel-9-nvidia",
				Workers:      "rhel-9-nvidia",
			},
			expectedOS: "rhcos9",
		},
		{
			name: "rhel-10 stream maps to rhcos10",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhel-10",
				Workers:      "rhel-10",
			},
			expectedOS: "rhcos10",
		},
		{
			name: "rhel-10.0 stream maps to rhcos10",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhel-10.0",
				Workers:      "rhel-10.0",
			},
			expectedOS: "rhcos10",
		},
		{
			name: "different rhel-9 minor versions map to same variant",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhel-9.4",
				Workers:      "rhel-9.6",
			},
			expectedOS: "rhcos9",
		},
		{
			name: "rhel-9 and rhel-10 streams produce rhcos9-10",
			clusterDataOS: clusterDataOS{
				ControlPlane: "rhel-9.6",
				Workers:      "rhel-10.0",
			},
			expectedOS: "rhcos9-10",
		},
		{
			name: "unrecognized stream name passes through",
			clusterDataOS: clusterDataOS{
				ControlPlane: "custom-os",
				Workers:      "custom-os",
			},
			expectedOS: "custom-os",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			variants := map[string]string{}
			if tt.releaseMajor != "" {
				variants[VariantReleaseMajor] = tt.releaseMajor
			}
			tt.clusterDataOS.setOS(logrus.WithField("test", "TestSetOS"), variants, "")
			assert.Equal(t, tt.expectedOS, variants[VariantOS])
		})
	}
}

func TestAdjustJobTierBasedOnView(t *testing.T) {
	views := []crview.View{
		testView("4.22-main", map[string][]string{
			"Architecture": {"amd64", "arm64", "multi"},
			"Platform":     {"aws", "azure", "gcp", "metal", "vsphere"},
			"Network":      {"ovn"},
			"JobTier":      {"blocking", "informing", "standard"},
			"Owner":        {"eng"},
		}),
	}

	tests := []struct {
		name         string
		variants     map[string]string
		expectedTier string
	}{
		{
			name: "blocking job matching all view variants stays blocking",
			variants: map[string]string{
				VariantRelease:  "4.22",
				VariantJobTier:  "blocking",
				VariantArch:     "amd64",
				VariantPlatform: "aws",
				VariantNetwork:  "ovn",
				VariantOwner:    "eng",
			},
			expectedTier: "blocking",
		},
		{
			name: "informing job with excluded platform becomes candidate",
			variants: map[string]string{
				VariantRelease:  "4.22",
				VariantJobTier:  "informing",
				VariantArch:     "amd64",
				VariantPlatform: "rosa",
				VariantNetwork:  "ovn",
				VariantOwner:    "eng",
			},
			expectedTier: "candidate",
		},
		{
			name: "standard job with excluded arch becomes candidate",
			variants: map[string]string{
				VariantRelease:  "4.22",
				VariantJobTier:  "standard",
				VariantArch:     "s390x",
				VariantPlatform: "aws",
				VariantNetwork:  "ovn",
				VariantOwner:    "eng",
			},
			expectedTier: "candidate",
		},
		{
			name: "candidate job is not adjusted even with excluded variant",
			variants: map[string]string{
				VariantRelease:  "4.22",
				VariantJobTier:  "candidate",
				VariantArch:     "s390x",
				VariantPlatform: "rosa",
				VariantNetwork:  "sdn",
				VariantOwner:    "chaos",
			},
			expectedTier: "candidate",
		},
		{
			name: "hidden job is not adjusted even with non-matching variants",
			variants: map[string]string{
				VariantRelease:  "4.22",
				VariantJobTier:  "hidden",
				VariantArch:     "s390x",
				VariantPlatform: "rosa",
				VariantNetwork:  "sdn",
				VariantOwner:    "chaos",
			},
			expectedTier: "hidden",
		},
		{
			name: "excluded job is not adjusted even with non-matching variants",
			variants: map[string]string{
				VariantRelease:  "4.22",
				VariantJobTier:  "excluded",
				VariantArch:     "s390x",
				VariantPlatform: "rosa",
				VariantNetwork:  "sdn",
				VariantOwner:    "chaos",
			},
			expectedTier: "excluded",
		},
		{
			name: "rare job is not adjusted even with non-matching variants",
			variants: map[string]string{
				VariantRelease:  "4.22",
				VariantJobTier:  "rare",
				VariantArch:     "s390x",
				VariantPlatform: "rosa",
				VariantNetwork:  "sdn",
				VariantOwner:    "chaos",
			},
			expectedTier: "rare",
		},
		{
			name: "job with no release is not adjusted",
			variants: map[string]string{
				VariantJobTier:  "blocking",
				VariantArch:     "s390x",
				VariantPlatform: "rosa",
			},
			expectedTier: "blocking",
		},
		{
			name: "job with release that has no view is not adjusted",
			variants: map[string]string{
				VariantRelease:  "4.15",
				VariantJobTier:  "blocking",
				VariantArch:     "s390x",
				VariantPlatform: "rosa",
			},
			expectedTier: "blocking",
		},
		{
			// If the view requires Platform to be in [aws, azure, gcp, metal, vsphere]
			// but the job doesn't have a Platform variant at all (e.g. couldn't be
			// determined from the job name), we should NOT downgrade. Absence of a
			// variant is not evidence of a mismatch — only a positive non-matching
			// value should trigger a downgrade.
			name: "job missing a view-filtered variant is not downgraded",
			variants: map[string]string{
				VariantRelease: "4.22",
				VariantJobTier: "blocking",
				VariantArch:    "amd64",
				// No Platform set — view requires Platform in [aws, azure, gcp, metal, vsphere]
				VariantNetwork: "ovn",
				VariantOwner:   "eng",
			},
			expectedTier: "blocking",
		},
		{
			name: "job with variant not specified in view is not filtered",
			variants: map[string]string{
				VariantRelease:  "4.22",
				VariantJobTier:  "blocking",
				VariantArch:     "amd64",
				VariantPlatform: "aws",
				VariantNetwork:  "ovn",
				VariantOwner:    "eng",
				VariantSuite:    "serial", // Suite not in view's include_variants
			},
			expectedTier: "blocking",
		},
		{
			name: "standard job with excluded network becomes candidate",
			variants: map[string]string{
				VariantRelease:  "4.22",
				VariantJobTier:  "standard",
				VariantArch:     "amd64",
				VariantPlatform: "aws",
				VariantNetwork:  "sdn",
				VariantOwner:    "eng",
			},
			expectedTier: "candidate",
		},
		{
			name: "standard job with excluded owner becomes candidate",
			variants: map[string]string{
				VariantRelease:  "4.22",
				VariantJobTier:  "standard",
				VariantArch:     "amd64",
				VariantPlatform: "aws",
				VariantNetwork:  "ovn",
				VariantOwner:    "qe",
			},
			expectedTier: "candidate",
		},
	}

	loader := &OCPVariantLoader{
		config: &v1.SippyConfig{},
		views:  views,
	}
	jLog := logrus.WithField("test", "TestAdjustJobTierBasedOnView")

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Copy variants to avoid mutation across tests
			variants := make(map[string]string)
			for k, v := range tt.variants {
				variants[k] = v
			}
			loader.adjustJobTierBasedOnView(jLog, "test-job", variants)
			assert.Equal(t, tt.expectedTier, variants[VariantJobTier])
		})
	}
}
