component_readiness:
    - name: 4.22-main
      base_release:
        release: "4.21"
        relative_start: now-60d
        relative_end: now-30d
      sample_release:
        release: "4.22"
        relative_start: now-3d
        relative_end: now
      test_id_options: {}
      test_filters: {}
      variant_options:
        column_group_by:
            Network: {}
            Platform: {}
            Topology: {}
        db_group_by:
            Architecture: {}
            FeatureSet: {}
            Installer: {}
            LayeredProduct: {}
            Network: {}
            Platform: {}
            Suite: {}
            Topology: {}
            Upgrade: {}
        include_variants:
            Architecture:
                - amd64
                - arm64
            FeatureSet:
                - default
                - techpreview
            Installer:
                - ipi
            LayeredProduct:
                - none
            Network:
                - ovn
            Platform:
                - aws
                - gcp
            Suite:
                - parallel
                - serial
                - unknown
            Topology:
                - ha
            Upgrade:
                - micro
                - minor
                - none
      advanced_options:
        minimum_failure: 3
        confidence: 95
        pity_factor: 5
        pass_rate_required_new_tests: 90
        pass_rate_required_all_tests: 0
        ignore_missing: false
        ignore_disruption: false
        flake_as_failure: false
        include_multi_release_analysis: true
      metrics:
        enabled: false
      regression_tracking:
        enabled: true
      automate_jira:
        enabled: false
      prime_cache:
        enabled: true
