-- +goose Up
-- +goose StatementBegin
CREATE TABLE schema_hashes(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    type varchar(32),
    name varchar(255),
    hash varchar(64)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE schema_hashes
-- +goose StatementEnd
