-- idx_test_daily_totals_date exists only to make an unscoped
-- SELECT MAX(date) FROM test_daily_totals fast across ~3,700 partitions.
-- TRT-2848 (incremental summary-table writer) removes the last two callers
-- that relied on that query (dailysummary.MaxSummaryDate and
-- cumulativesummary.MaxDailySummaryDate), so this index is now pure write
-- overhead: every insert into test_daily_totals maintains it for no reader.
--
-- Do not deploy this migration before TRT-2848 lands: MaxSummaryDate and
-- MaxDailySummaryDate are still on the hot path on main today, and without
-- this index they fall back to a full scan across every partition.
DROP INDEX IF EXISTS idx_test_daily_totals_date;
