-- TRT-1989: Create Partitioned Tables
--
-- Creates 3 partitioned tables using nested LIST→RANGE partitioning:
-- - Level 1: LIST partition by release (e.g., "4.17", "4.18")
-- - Level 2: RANGE sub-partition by timestamp/date (daily granularity)
--
-- Tables:
--   - prow_job_run_tests (LIST by prow_job_run_release → RANGE by prow_job_run_timestamp)
--   - prow_job_run_test_outputs (LIST by prow_job_run_test_release → RANGE by prow_job_run_test_timestamp)
--   - test_analysis_by_job_by_dates (LIST by release → RANGE by date)
--
-- Partition creation (release partitions + daily sub-partitions) is handled separately
-- via partition management system.

-- ============================================================================
-- 1. prow_job_run_tests
-- ============================================================================

CREATE TABLE IF NOT EXISTS prow_job_run_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,

    prow_job_run_id BIGINT NOT NULL,
    prow_job_id BIGINT NOT NULL,
    prow_job_run_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    prow_job_run_release TEXT NOT NULL,
    test_id BIGINT NOT NULL,
    suite_id BIGINT,
    status INT,
    duration DOUBLE PRECISION,

    PRIMARY KEY (id, prow_job_run_release, prow_job_run_timestamp)
) PARTITION BY LIST (prow_job_run_release);

-- Indexes for prow_job_run_tests
-- Note: timestamp first in composite for range filter optimization
CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_release_timestamp
    ON prow_job_run_tests (prow_job_run_timestamp, prow_job_run_release);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_prow_job_run_id
    ON prow_job_run_tests (prow_job_run_id);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_test_id
    ON prow_job_run_tests (test_id);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_status
    ON prow_job_run_tests (status);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_prow_job_id
    ON prow_job_run_tests (prow_job_id);

-- Composite index for Component Readiness queries
CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_test_id_status
    ON prow_job_run_tests (test_id, status);

-- ============================================================================
-- 2. prow_job_run_test_outputs
-- ============================================================================

CREATE TABLE IF NOT EXISTS prow_job_run_test_outputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,

    prow_job_run_test_id BIGINT NOT NULL,
    output TEXT,
    prow_job_run_test_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    prow_job_run_test_release TEXT NOT NULL,

    PRIMARY KEY (id, prow_job_run_test_release, prow_job_run_test_timestamp)
) PARTITION BY LIST (prow_job_run_test_release);

-- Indexes for prow_job_run_test_outputs
CREATE INDEX IF NOT EXISTS idx_prow_job_run_test_outputs_release_timestamp
    ON prow_job_run_test_outputs (prow_job_run_test_timestamp, prow_job_run_test_release);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_test_outputs_prow_job_run_test_id
    ON prow_job_run_test_outputs (prow_job_run_test_id);

-- ============================================================================
-- 3. test_analysis_by_job_by_dates
-- ============================================================================

CREATE TABLE IF NOT EXISTS test_analysis_by_job_by_dates (
    date TIMESTAMP WITH TIME ZONE,
    test_id BIGINT,
    release TEXT NOT NULL,
    job_name TEXT,
    test_name TEXT,
    runs BIGINT,
    passes BIGINT,
    flakes BIGINT,
    failures BIGINT
) PARTITION BY LIST (release);

-- Indexes for test_analysis_by_job_by_dates
-- Unique index matching the original test_release_date constraint
CREATE UNIQUE INDEX IF NOT EXISTS idx_test_analysis_test_release_date
    ON test_analysis_by_job_by_dates (date, test_id, release, job_name);

-- Index matching the original test_analysis_name_and_job index
CREATE INDEX IF NOT EXISTS idx_test_analysis_name_and_job
    ON test_analysis_by_job_by_dates (test_name, job_name);
