-- TRT-1989: Create Partitioned Tables
--
-- Creates partitioned tables using nested LIST→RANGE partitioning:
-- - Level 1: LIST partition by release (e.g., "4.17", "4.18")
-- - Level 2: RANGE sub-partition by timestamp/date (daily granularity)
--
-- Tables:
--   - prow_job_runs (LIST by prow_job_release → RANGE by timestamp)
--   - prow_job_run_annotations (LIST by prow_job_run_release → RANGE by prow_job_run_timestamp)
--   - prow_job_run_prow_pull_requests (LIST by prow_job_run_release → RANGE by prow_job_run_timestamp)
--   - prow_job_run_tests (LIST by prow_job_run_release → RANGE by prow_job_run_timestamp)
--   - prow_job_run_test_outputs (LIST by prow_job_run_test_release → RANGE by prow_job_run_test_timestamp)
--   - test_analysis_by_job_by_dates (LIST by release → RANGE by date)
--
-- No foreign key constraints are created on partitioned tables. Referential
-- integrity is maintained by the application layer (prowloader) and partition
-- lifecycle management. See docs/plans/trt-1989-phase4-partitioned-tables.md.
--
-- Partition creation (release partitions + daily sub-partitions) is handled
-- separately via the partition management system.

-- ============================================================================
-- 1. prow_job_runs
-- ============================================================================

CREATE TABLE IF NOT EXISTS prow_job_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,

    prow_job_id BIGINT NOT NULL,
    prow_job_release TEXT NOT NULL,
    cluster TEXT,
    gcs_bucket TEXT,
    url TEXT,
    test_failures BIGINT,
    failed BOOLEAN,
    infrastructure_failure BOOLEAN,
    known_failure BOOLEAN,
    succeeded BOOLEAN,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    duration BIGINT,
    overall_result TEXT,
    labels TEXT[],
    test_flakes BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (id, prow_job_release, timestamp)
) PARTITION BY LIST (prow_job_release);

-- Indexes for prow_job_runs
CREATE INDEX IF NOT EXISTS idx_prow_job_runs_prow_job_id
    ON prow_job_runs (prow_job_id);

CREATE INDEX IF NOT EXISTS idx_prow_job_runs_release_timestamp
    ON prow_job_runs (prow_job_release, timestamp);

CREATE INDEX IF NOT EXISTS idx_prow_job_runs_timestamp
    ON prow_job_runs (timestamp);

-- ============================================================================
-- 2. prow_job_run_annotations
-- ============================================================================

CREATE TABLE IF NOT EXISTS prow_job_run_annotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,

    prow_job_run_id BIGINT NOT NULL,
    key TEXT NOT NULL,
    value TEXT,
    prow_job_run_release TEXT NOT NULL,
    prow_job_run_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,

    PRIMARY KEY (id, prow_job_run_release, prow_job_run_timestamp)
) PARTITION BY LIST (prow_job_run_release);

-- Indexes for prow_job_run_annotations
-- Unique constraint includes partition keys (required for partitioned tables)
CREATE UNIQUE INDEX IF NOT EXISTS idx_prow_job_run_annotations_key
    ON prow_job_run_annotations (prow_job_run_id, key, prow_job_run_release, prow_job_run_timestamp);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_annotations_release_timestamp
    ON prow_job_run_annotations (prow_job_run_release, prow_job_run_timestamp);

-- ============================================================================
-- 3. prow_job_run_prow_pull_requests
-- ============================================================================

CREATE TABLE IF NOT EXISTS prow_job_run_prow_pull_requests (
    prow_job_run_id BIGINT NOT NULL,
    prow_pull_request_id BIGINT NOT NULL,
    prow_job_run_release TEXT NOT NULL,
    prow_job_run_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,

    PRIMARY KEY (prow_job_run_id, prow_pull_request_id, prow_job_run_release, prow_job_run_timestamp)
) PARTITION BY LIST (prow_job_run_release);

-- Indexes for prow_job_run_prow_pull_requests
CREATE INDEX IF NOT EXISTS idx_prow_job_run_prow_pull_requests_prow_pull_request_id
    ON prow_job_run_prow_pull_requests (prow_pull_request_id);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_prow_pull_requests_release_timestamp
    ON prow_job_run_prow_pull_requests (prow_job_run_release, prow_job_run_timestamp);

-- ============================================================================
-- 4. prow_job_run_tests
-- ============================================================================

CREATE TABLE IF NOT EXISTS prow_job_run_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,

    prow_job_run_id BIGINT NOT NULL,
    prow_job_id BIGINT NOT NULL,
    prow_job_run_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    prow_job_run_release TEXT NOT NULL,
    test_id BIGINT NOT NULL,
    suite_id BIGINT,
    status INT,
    duration DOUBLE PRECISION,

    PRIMARY KEY (id, prow_job_run_release, prow_job_run_timestamp)
) PARTITION BY LIST (prow_job_run_release);

-- Indexes for prow_job_run_tests
-- Note: timestamp first in composite for range filter optimization
CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_release_timestamp
    ON prow_job_run_tests (prow_job_run_timestamp, prow_job_run_release);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_prow_job_run_id
    ON prow_job_run_tests (prow_job_run_id);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_test_id
    ON prow_job_run_tests (test_id);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_status
    ON prow_job_run_tests (status);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_prow_job_id
    ON prow_job_run_tests (prow_job_id);

-- Composite index for Component Readiness queries
CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_test_id_status
    ON prow_job_run_tests (test_id, status);

-- ============================================================================
-- 5. prow_job_run_test_outputs
-- ============================================================================

CREATE TABLE IF NOT EXISTS prow_job_run_test_outputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,

    prow_job_run_test_id BIGINT NOT NULL,
    output TEXT,
    prow_job_run_test_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    prow_job_run_test_release TEXT NOT NULL,

    PRIMARY KEY (id, prow_job_run_test_release, prow_job_run_test_timestamp)
) PARTITION BY LIST (prow_job_run_test_release);

-- Indexes for prow_job_run_test_outputs
CREATE INDEX IF NOT EXISTS idx_prow_job_run_test_outputs_release_timestamp
    ON prow_job_run_test_outputs (prow_job_run_test_timestamp, prow_job_run_test_release);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_test_outputs_prow_job_run_test_id
    ON prow_job_run_test_outputs (prow_job_run_test_id);

-- ============================================================================
-- 6. test_analysis_by_job_by_dates
-- ============================================================================

CREATE TABLE IF NOT EXISTS test_analysis_by_job_by_dates (
    date TIMESTAMP WITH TIME ZONE,
    test_id BIGINT,
    release TEXT NOT NULL,
    job_name TEXT,
    test_name TEXT,
    runs BIGINT,
    passes BIGINT,
    flakes BIGINT,
    failures BIGINT
) PARTITION BY LIST (release);

-- Indexes for test_analysis_by_job_by_dates
-- Unique index matching the original test_release_date constraint
CREATE UNIQUE INDEX IF NOT EXISTS idx_test_analysis_test_release_date
    ON test_analysis_by_job_by_dates (date, test_id, release, job_name);

-- Index matching the original test_analysis_name_and_job index
CREATE INDEX IF NOT EXISTS idx_test_analysis_name_and_job
    ON test_analysis_by_job_by_dates (test_name, job_name);
